CHANGELOG.md, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, pubspec.yaml
Hi there. Here is I have tried to update to AndroidX. Please take a look on it. As many libs already updated. It is like a Flash mob from Google ) Cheers
=> Breaking change. Update to AndroidX

CHANGELOG.md, README.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java, example/android/app/src/main/AndroidManifest.xml, example/lib/main.dart, lib/file_picker.dart, pubspec.yaml
**Rollback - Breaking change:** Re-adds runtime verification for external storage read permission. Don't forget to add the permission to the `AndroidManifest.xml` file as well. More info in the README file.
**Bug fix:** Fixes a crash that could cause some Android API to crash when multiple files were selected from external storage.
=> Beta (1.3.7)

README.md
Sample for single file is the same than multiple files. This is a minor fix but could confuse someone.
=> fix usage sample for single file

go/go.mod
The rename of this repository broke `go get` when the developer uses Go Modules to import this plugin (which is the default when using hover to setup a go-flutter project).
```
github.com/miguelpruivo/flutter_file_picker/go: github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20191120004853-c99e22e95874: parsing go.mod:
module declares its path as: github.com/miguelpruivo/plugins_flutter_file_picker/go
but was required as: github.com/miguelpruivo/flutter_file_picker/go
```
This PR fixes that by aligning the `module` declaration with the repo path.
=> Fix Go module declaration

CHANGELOG.md, example/ios/Flutter/Flutter.podspec, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, go/plugin.go, ios/Classes/FilePickerPlugin.m, lib/file_picker.dart, pubspec.yaml
- Fixes an issue that could result in a crash when selecting files (with repeated taps) from 3rd party remote providers (Google Drive, Dropbox etc.);
- Go: Updates channel name;
- Adds check that ensures that you one uses `FileType.custom` when providing a custom file extension filter;
=> Fixes (#200) and other minor improvements

go/file_windows.go, go/go.mod
fixes
```
github.com/miguelpruivo/flutter_file_picker/go
/go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200417122615-c13124f9bb41/file_windows.go:24:22: syntax error: unexpected extensions at end of statement
```
and
```
github.com/marchellodev/flutter_file_picker/go
/go/pkg/mod/github.com/marchellodev/flutter_file_picker/go@v0.0.0-20200418121646-69eca38c82b7/file_windows.go:4:2: imported and not used: "strings"
/go/pkg/mod/github.com/marchellodev/flutter_file_picker/go@v0.0.0-20200418121646-69eca38c82b7/file_windows.go:26:26: undefined: resolveType
```
=> fixes windows support

lib/file_picker.dart
when building for web, it fails on import mismatch, because file_picker.dart is taking File object from dart:io but your web implementation is taking it from dart:html. It is correctly declared in file_picker_stub.dart, but not here
=> import fix

ios/file_picker.podspec
This resolves the [issue](https://github.com/miguelpruivo/flutter_file_picker/issues/233#issuecomment-620264779) we discussed regarding [flutter_image_cropper](https://pub.dev/packages/image_cropper) and [DKImagePicker](https://github.com/zhangao0086/DKImagePickerController) both importing [TOCropViewController](https://github.com/TimOliver/TOCropViewController) and causing a conflict.
`DKImagePicker` exposes subspecs -- from those, I was able to select this package to only import the `PhotoGallery` subspec, which excludes `TOCropViewController`.
I'm new to this world of Pods, etc so if I messed anything up, be gentle 🤣
=> fix conflict with flutter_image_cropper

file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java
Fixes error: java.lang.RuntimeException: Unable to destroy activity {package.name/package.name.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mr.flutter.plugin.filepicker.FilePickerDelegate.setEventHandler(io.flutter.plugin.common.EventChannel$EventSink)' on a null object reference
=> Fix error when closing app on Android

file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
Opening a PR for File Picker Support for devices with Android Q and above.
Implemented OS level check to get file path for the selected file.
Verified this implementation on devices with Android Q and below as well, it is working as expected.
#234
=> Added File Picker Support for Android Q and above

file_picker/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
@miguelpruivo , please merge this PR which resolves the issue when the user selects a file from **Downloads** folder and the content uri is not able to resolve to a file path so in turn the file path is returned as null. (happens on devices below Android Q)
This PR resolves this issue, when the file path is null then it will create a file from uri and save it in app cache dir so the file will be accessible within the app.
Thanks!
=> Urgent Bug Fix for null path for file selection in Downloads folder for OS below Android Q

file_picker/go/file_darwin.go, file_picker/pubspec.yaml, file_picker_platform_interface/lib/method_channel_file_picker.dart
Getting a directory path was not working on osx for me so I changed the implementation from the go dlgs dependency to applescript like the file implementation that was working. I was able to confirm that with my changes directory picking works on osx, linux, and windows. This addresses issue #324
=> Macos directory fix

go/file_linux.go
This pull request fixes a bug which I came across on Linux (this bug existed already before the new major release 2.0.0).
Previously, the file filter argument was set to `*.*` which somehow led to the effect that all directories are displayed as not clickable / selectable in the directory picker dialog on Linux (Ubuntu 19). This effect can be observed on the screenshot below. All directories are greyed-out and cannot be selected (except the bookmarks / default directories on the left side):
As stated in the docs of [gen2brain/dlgs](https://github.com/gen2brain/dlgs/blob/master/file_linux.go), setting the file filter to a blank string will display all file types:
```go
// File displays a file dialog, returning the selected file or directory, a bool for success, and an
// error if it was …
```
=> Fix bug for directory picking on Linux: drop file type filter

ios/Classes/FilePickerPlugin.m
The getDirectoryPath() doesn't work when access to the directory is not available.
This PR changes to use NSDocumentDirectory on iOS 12 or lower.
https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories
=> Directory access is not available on iOS 12 or lower

lib/file_picker.dart
#493 Fix flutter web warning "Don't import implementation files from another package."
=> Fix flutter web warning in generated_plugin_registrant.dart

lib/src/platform_file.dart
Multiple people encountered an error where calling PlatformFile.extension returns a null, like issue #491 
I've created a simple fix for this one. Hope it will help other struggling to create a fix for this.
=> Fix null PlatformFIle.extension error when called on Web

lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_web.dart, lib/src/platform_file.dart
Should work with Flutter Web and IO. Also see #465
Can for example be used with a multipart file upload.
=> Added withReadStream option to load a file in chunks (useful for large files which don't fit in RAM)

android/src/main/java/com/mr/flutter/plugin/filepicker/FileInfo.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
On Android file_picker would crash if the number of bytes for a file exceeds the JAVA integer limit (2^32 bytes) so with this PR the limit should be at 2^64 bytes or the JAVA long limit.
Minimum steps to reproduce
```dart
Future<void> pick() async {
...
await FilePicker.platform.pickFiles();
...
}
```
Then once the picker launches pick a file with more than 2.1 GB, file_picker will crash with java.lang.NumberFormatException
=> [Android][Bug fix]use long instead of int to represent no. of bytes  when parsing file sizes

android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
References #661 where we can use the Gallery picker instead of the file manager to pick images on Android, which makes the process to pick an image more streamlined as a user won't have to navigate through files with a similar gallery presented through the MediaStore API.
I've tested the changes and made sure normal picking as well as image picking, both in single and multiple items work.
Let me know if anything needs to be changed!
=> Utilize a Gallery-Based picker for Android for Images

android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
=> Fix getDirectoryPath()

android/build.gradle, example/android/build.gradle, pubspec.yaml
Simple PR to reduce a few warnings Android release builds will emit when compiling against this package.
=> Migrate jcenter pointers to mavenCentral

CHANGELOG.md, example/lib/generated_plugin_registrant.dart, lib/src/file_picker_result.dart, lib/src/platform_file.dart, pubspec.yaml
Hi ! I was recently trying to compare platformFiles but realized they weren't really comparing that well.
This is a small PR that adds `==`, `hashCode` and `toString` to `FilePickerResult` and `PlatformFile`.
=> Add custom equality and toString

CHANGELOG.md, lib/src/platform_file.dart, lib/src/utils.dart, pubspec.yaml, test/common.dart, test/file_picker_utils_test.dart
Fixes #856:
`.app` files on macOS are special files which are actually Unix directories ([read more on StackExchange](https://apple.stackexchange.com/a/112213)). Previously, if an `.app` file was picked, then we would get the following exception because directories don't have an inherent (file) size:
```
FileSystemException: Cannot retrieve length of file, path = '/path/Runner.app' (OS Error: Is a directory, errno = 21)
```
I changed the implementation so that the **file size is only determined**, if the picked file system entity is an **actual file** (and not a directory). If the picked file system entity is **not a file**, then the file size will **default to zero** because it the `size` property is non-nullable.
@miguelpruivo, are you okay with this solution or would you suggest a …
=> Fixes bug #856 that .app files could not be picked on macOS

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, lib/src/file_picker_linux.dart, lib/src/file_picker_macos.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml, test/file_picker_linux_test.dart, test/file_picker_macos_test.dart, test/file_picker_windows_test.dart
Fixes #871 
Users could click on `All Files(*.*)` in the bottom right dropdown even though a file filter was enabled:
* I improved the bug report template so that the checkboxes are always correctly rendered like this:
* Previously, the default file type filters (`FileType.audio`, `FileType.image`, etc.) weren't aligned on all three desktop platforms. I fixed it so that for example `FileType.Audio` filters for `*.aac`, `*.midi`, `*.mp3`, `*.ogg`, and `*.wav` **on all three platforms**.
There's one more bug under macOS which I wasn't able to fix (see TODO in `test/file_picker_macos_test.dart`).
=> #871: file extensions not enforced on Windows

CHANGELOG.md, lib/src/windows/file_picker_windows.dart, pubspec.yaml
fixes #918. With this change, it is possible to select at least 2300 files (even files with extra long file paths such as `C:\Users\phil\Downloads\abcdefghijklmnopqrstuvxyz0123456789\zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.txt`. Please see commit message for detailed explanation: 7450ae6
=> #918: buffer for selected file paths too small on windows

CHANGELOG.md, analysis_options.yaml, lib/_internal/file_picker_web.dart, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_linux.dart, lib/src/file_picker_macos.dart, lib/src/windows/file_picker_windows.dart, lib/src/windows/file_picker_windows_ffi_types.dart, pubspec.yaml
- Added implementation lock the main flutter window  behind the file picker window when `lockParentWindow` is set to `true`
without lock(default, how it is today):
with lock(when set):
=> Added option to lock the parent window(flutter window) when file picker is open

CHANGELOG.md, lib/src/file_picker_linux.dart, pubspec.yaml
Following up #932 #934(ignore please, I did not see the revert)
=> Added kdialog arguments, bumped to version 4.3.1

CHANGELOG.md, lib/_internal/file_picker_web.dart, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart, lib/src/linux/dialog_handler.dart, lib/src/linux/file_picker_linux.dart, lib/src/linux/kdialog_handler.dart, lib/src/linux/qarma_and_zenity_handler.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml, test/file_picker_macos_test.dart, test/linux/kdialog_handler_test.dart, test/linux/qarma_and_zenity_handler_test.dart
Implements #859 for Linux, macOS, and Windows.
I added the parameter `initialDirectory` to all three methods `pickFiles()`, `getDirectoryPath()`, and `saveFile()`. This optional parameter must contain an **absolute** path to the directory where the dialog should open. 
Example code:
```dart
await FilePicker.platform.pickFiles(
initialDirectory: '/home/johnDoe/workspace',
);
await FilePicker.platform.getDirectoryPath(
initialDirectory: '/home/johnDoe/workspace',
);
await FilePicker.platform.saveFile(
initialDirectory: '/home/johnDoe/workspace',
);
```
I was able to successfully implement and test the Linux and macOS implementations. Only the Windows implementation does not work completely:
* **Linux:**
* **macOS:**
* **Windows:**
=> Feature for desktop platforms: initial directory

CHANGELOG.md, README.md, lib/src/file_picker.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Changes the implementation of `getDirectoryPath` on Windows so that the dialog looks like other, modern Windows dialogs as requested in #915.
| Previously, the folder picker dialog looked like this: | With this PR |
| ---------- | ------------ |
| ![grafik](https://user-images.githubusercontent.com/9049899/154863194-9e723c54-c591-405b-9d28-a134ef9cac2d.png) | ![grafik](https://user-images.githubusercontent.com/9049899/154863262-0dba5b96-c4f7-414f-b709-dd4f2df6d1ab.png)              |
**Win32:**
For this PR, I switched from `SHBrowseForFolderW` to [Microsoft's `IFileDialog`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialog) and therefore added `win32` as a dependency. `win32` is written by Flutter's product manager (Tim Sneath) and simplifies …
=> #915 modern directory picker on Windows

CHANGELOG.md, ios/Classes/FilePickerPlugin.h, ios/Classes/FilePickerPlugin.m, ios/file_picker.podspec, pubspec.yaml
Enable conditional compilation of the media, audio and documents pickers for iOS.
This prevents error messages for permissions (NSPhotoLibraryUsageDescription, NSAppleMusicUsageDescription, etc.) when publishing to app store connect, in case you don't need either category.
This addresses #783 in a different way.
Additional usage instructions that should be added to: https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#ios
---
You can prevent the need for certain permissions by excluding compilation of Media, Audio or Documents picker respectively.
This is achieved by including in the file ```<project root>/ios/Podfile``` the line ```Pod::PICKER_MEDIA = false```, resp. ```Pod::PICKER_AUDIO = false```, resp. ```Pod::PICKER_DOCUMENT = false``` before the line ```target 'Runner' …
```
=> Add conditional compilation of media, audio and document pickers for iOS

.github/workflows/main.yml, CHANGELOG.md, example/lib/generated_plugin_registrant.dart, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart, lib/src/linux/kdialog_handler.dart, lib/src/linux/qarma_and_zenity_handler.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
I have an issue with library because I want to use `ffi` version >= 2.0.0, but file picker requires `ffi` < 2.0.0
So I updated all the dependencies. Because I changed to `lints` 2.0.0, I fixed problems a bit
Tests are passed:
- file_picker_macos_test.dart
- file_picker_utils_test.dart
Can't process windows and linux tests because I ran it on MacOS machine
=> Updated dependencies

android/build.gradle, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
- Changed `compileSdkVersion` to 33 in `build.gradle`.
- Android specific platform channel implementation no longer requests `READ_EXTERNAL_STORAGE` on Android 13 or higher
_i.e._ SDK 33 or above.
Closes #1099.
Closes #1107.
To be frank, I couldn't find any sources about requirement of `READ_EXTERNAL_STORAGE` for `ACTION_GET_CONTENT`.
However, `READ_EXTERNAL_STORAGE` should no longer be used when targeting Android 13 or higher. It does nothing on newer versions, however you can keep it in `AppManifest.xml`.
The storage access has been split into three permissions:
<html>
<body>
Type of media | Permission to request
-- | --
Images and photos | READ_MEDIA_IMAGES
Videos | READ_MEDIA_VIDEO
Audio files | READ_MEDIA_AUDIO
See: https://developer.android.com/about/versions/13/behavior-changes-13. …
=> fix: package not working with Android 13 (SDK 33)

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java, pubspec.yaml
Currently file picker caches every single file in android . This method is inefficient when the file size is too large. This fix removes unnecessary caching and loading issue. It will cache only if it cannot retrieve the paths directly (only files in downloads folder will be cached ). This will save a lot of time by eliminating delay which is caused due to caching. (Caching issue is android specific )
=> fix caching issue

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, pubspec.yaml
Android:
Replaced the build variable `Build.VERSION_CODES.TIRAMISU` with its integer `33`.
This variable is not available if the app is targeting sdk 32 or lower, hence resulting in a compile error.
Fixes issues #1140 and #1124
=> Android tiramisu fix

CHANGELOG.md, ios/Classes/FilePickerPlugin.m, pubspec.yaml
When picking multiple live photos where the key photo was changed, the same one is returned multiple times.
This is because the filename used when converting the photo from pvt to jpeg is the same for all pictures where the key photo was updated.
For example, here is the content of a regular live photo:
```
IMG_0042.pvt
|- IMG_0042.MOV
|- metadata.plist
|- IMG_0042.HEIC
```
After the key photo is changed, the content changes to:
```
IMG_0042.pvt
|- FullSizeRender.mov
|- metadata.plist
|- FullSizeRender.heic
```
This solves the issue by using the original filename (e.g. `IMG_0042.pvt`) instead of the renamed file (`FullSizeRender.heic`).
=> Fix an issue when picking live photos where the key photo was changed

CHANGELOG.md, README.md, pubspec.yaml
Updates the dependency `win32`, which is used in our Windows `file_picker` implementation, to the latest major v4. See `win32`'s changelog: https://pub.dev/packages/win32/changelog
=> #1255: update dependency `win32` to latest major v4

CHANGELOG.md, example/pubspec.yaml, pubspec.yaml
This PR updates file_picker to support Dart 3.
Any null-safe applications (Dart 2.12+) are Dart 3 compatible.
@miguelpruivo This unblocks people using Dart 3
Fixes #1288
=> Bump Dart to 3.0

CHANGELOG.md, ios/Classes/FilePickerPlugin.m, pubspec.yaml
This PR fixes the No such file or directory on ios devices.
the issue is caused by the os abnormal behavior of deleting the `app_id-Inbox/` directory within minutes instead of waiting for the app to be terminated and then cleaning up temp files.
moved the picked files one level above the original dir, the image_picker package is also doing a similar thing until Apple fixes this behavior.
=> fix the No such file or directory ios issue

CHANGELOG.md, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Fixed crash when picking a directory. [https://github.com/https://github.com/miguelpruivo/flutter_file_picker/issues/1317, https://github.com/https://github.com/miguelpruivo/flutter_file_picker/issues/1297]
"Note that, with v5.0.0, .release() is also called automatically if you wish to upgrade it." https://win32.pub/docs/com-programming/basics#releasing-com-objects
=> Fixed crashing on windows when picking a directory

CHANGELOG.md, ios/Classes/FilePickerPlugin.m, pubspec.yaml
This PR contains fixes for the following:
- When you selected multiple images and for some reason they had the same file name the plugin would not properly handle the situation and would cause the same file to be repeated on all selected files instead of the files itself.
- When you select multiple images the resulting list order would be different than the originally selected order by the user.
=> [iOS][Gallery] - Multi image selection fixes

CHANGELOG.md, lib/_internal/file_picker_web.dart, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart, lib/src/linux/file_picker_linux.dart, lib/src/windows/file_picker_windows.dart
Currently the order of the imported files in web is not respected. It seems like files are ordered by filesize. 
To have the feature to keep the picking order, the files are read synchronously.  
With `readSequential` order of files will be kept in web. The default value is false.
=> Feature: keep picking order on web

lib/src/platform_file.dart
Maybe I am not too bright, but wasted a lot of time thinking a null check would correctly work around being on a web renderer. :sweat_smile:
=> fix exception message

lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart
* Allow m4v files in FileType.media filter
* throw if caller tries to use allowedExtensiosn with any file type other than custom
=> Minor fixes

android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java, example/android/app/build.gradle
Compression is done by reading the file on disk, which is not allowed on Android 14+. 
The correct way is opening the content Uri with openInputStream().
=> Fix #1455 NPE when compressing images from gallery on Android 14

android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
prevent be replaced by same file name
fix to https://github.com/miguelpruivo/flutter_file_picker/issues/1464
=> add store in folder by millis

CHANGELOG.md, lib/src/file_picker.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Hi, thanks for developing and maintaining this plugin!
Here is a fix for issue #970 (getDirectoryPath() would ignore its initialDirectory parameter on Windows). I hope you'll find it helpful.
=> #970 Support setting an initial directory in getDirectoryPath() on Windows 

CHANGELOG.md, README.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, ios/Classes/FilePickerPlugin.m, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart, lib/src/linux/file_picker_linux.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
User can save file to mobile platforms with bytes. Desktop platforms remain unchanged.
=> Save file to mobile platforms.

CHANGELOG.md, lib/_internal/file_picker_web.dart, pubspec.yaml
When built in the html web-renderer, an error may occur:
TypeError: Instance of 'NativeByteBuffer': type 'NativeByteBuffer' is not a subtype of type 'List<int>'.
Therefore, we need to make a type discrimination of the reader.result.
=> Fix: TypeError: Instance of 'NativeByteBuffer': type 'NativeByteBuffer' is not a subtype of type 'List'.

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, pubspec.yaml
Fixes https://github.com/miguelpruivo/flutter_file_picker/issues/1526.
Tested by building the `flutter_file_picker` example app with the changes in https://github.com/flutter/engine/pull/52022 applied.
=> Remove references to v1 embedding

README.md
The demo GIFs on pub.dev were not displayed on pub.dev. See #1513 
I copied the image address from GitHub:
https://github.com/miguelpruivo/flutter_file_picker/assets/24459435/c15acbb1-bbc0-4b41-b989-de608293daea
Tested it by replacing the new URLs in Chrome Dev Tools.
Closes #1513
=> Fix demo GIFs in README.md on pub.dev

CHANGELOG.md, lib/_internal/file_picker_web.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
There's a memory leak happening with web version
<details>
<summary>See here</summary>
```Dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
void main() => runApp(const MyApp());
class MyApp extends StatelessWidget {
const MyApp({super.key});
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Material App',
home: FirstScreen(),
);
}
}
class FirstScreen extends StatelessWidget {
const FirstScreen({super.key});
@override
Widget build(BuildContext context) {
return Scaffold(
body: Center(
child: TextButton(
onPressed: () {
Navigator.push(
context,
MaterialPageRoute(builder: (context) => const SecondScreen()),
);
},
child: Text('Go to second screen'),
),
),
);
}
}
class SecondScreen extends StatefulWidget {
const …
```
=> [Web] Release picked file data for Web

CHANGELOG.md, android/build.gradle, example/android/app/build.gradle, pubspec.yaml
This PR updates the minimum Android SDK version to 21, to align with the current minimum on Flutter 3.22.
It also updates the compile & target SDK versions to 34 and fixes a versioning issue for win32.
In a follow-up PR, I will also migrate the plugin to Gradle 8.
Fix was tested by compiling and running the example app on an Android 14 device.
Fixes #1522
Fixes #1528 
Fixes https://github.com/miguelpruivo/flutter_file_picker/issues/1531
=> Fix: Bump min Android SDK version

CHANGELOG.md, lib/_internal/file_picker_web.dart, lib/src/windows/file_picker_windows_ffi_types.dart, pubspec.yaml, test/file_picker_macos_test.dart, test/file_picker_utils_test.dart, test/file_picker_windows_test.dart, test/linux/dialog_handler_test.dart, test/linux/kdialog_handler_test.dart, test/linux/qarma_and_zenity_handler_test.dart
This PR bumps the `web` dependency to 1.0.0
It also bumps the minimum Flutter version to 3.22.0, which ships with Dart 3.4.0
That Dart version is the minimum needed for the new package:web version.
It also addresses the following points:
- the structs in the ffi types for windows should be marked base, sealed or final, due to a Dart language change. I made them final.
- the web version of this plugin had two open TODO's that needed Dart 3.4, these have been fixed.
- the web version also had a redundant static variable `platform`, that wasn't used except for setting up the web platform implementation. This has been removed, as users should not rely on `FilePickerWeb.platform`, but rather on `FilePicker.platform`
Fixes #1571 
Closes …
=> Bump `package:web` to 1.0.0

CHANGELOG.md, example/web/index.html, pubspec.yaml
This PR fixes the example for the web, that now needs a different method of bootstrapping in Flutter 3.22
I had forgotten to include this commit in my last PR, after testing the web example.
We still hit the CanvasKit undefined module error when running the example a second time, but this was reported upstream in flutter/flutter.
=> Fix web example on Flutter 3.22

CHANGELOG.md, ios/Classes/FilePickerPlugin.m, pubspec.yaml
=> Safely call the result block

lib/src/linux/kdialog_handler.dart, lib/src/linux/qarma_and_zenity_handler.dart, lib/src/windows/file_picker_windows.dart, test/file_picker_windows_test.dart
adding support for the “m4a” format
=> adding support for the “m4a” format

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, pubspec.yaml
fixing this https://github.com/miguelpruivo/flutter_file_picker/issues/1643
=> removing v1 embedding to fix compile on flutter 3.27

CHANGELOG.md, ios/Classes/FilePickerPlugin.m, pubspec.yaml
Currently, the iOS image picker fails entirely if any single image fails to process, causing a poor user experience.
Error: 
`PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x303587d50 {Error Domain=NSCocoaErrorDomain Code=4099 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x303572be0 {Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 18859 named (null) was invalidated." UserInfo={NSDebugDescription=The connection to service with pid 18859 named (null) was invalidated.}}}}}, null)`
Updated the PHPicker …
=> fix(iOS): 🐛 Image Picker to Handle Partial Failures Gracefully

lib/src/file_picker_macos.dart, lib/src/linux/kdialog_handler.dart, lib/src/linux/qarma_and_zenity_handler.dart, lib/src/windows/file_picker_windows.dart, test/linux/kdialog_handler_test.dart, test/linux/qarma_and_zenity_handler_test.dart
This PR fixes some failing checks due to https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unreachable_switch_default#unreachable_switch_default
The one in MacOS is fixed by #1690 
This unblocks landing #1690
=> chore: fix unreachable switch default

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, pubspec.yaml
This pull request targets the issue https://github.com/miguelpruivo/flutter_file_picker/issues/1700 and uses the solution from the discussion in https://github.com/miguelpruivo/flutter_file_picker/issues/1404 to fix pickFiles when launchMode="singleInstance" is configured in AndroidManifest.xml
=> fix (Android) pickFiles with launchMode=singleInstance

CHANGELOG.md, analysis_options.yaml, example/android/.gitignore, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- `unsafe_html` was removed in Dart 3.7.0
- `enableGPUValidationMode` in macOS and iOS.
- Added `.cxx` folder to `.gitignore`.
=> Flutter 3.29 Migration

CHANGELOG.md, pubspec.yaml
This pull request introduces a breaking change for macOS users of the `flutter_file_picker` package.  
Starting from version **8.3.0**, the `pickFiles()` method now requires the entitlement `com.apple.security.files.user-selected.read-only` on macOS. If this entitlement is not present, the method will return `null` and the file picker will not open, potentially leading to confusion among developers upgrading from previous versions where this entitlement was not required.  
- This change was introduced silently in version **8.3.0** without clear documentation, which can cause issues for developers who may not be aware of the requirement.
- To ensure a smooth transition and proper functionality of the file picker on macOS, it is crucial to document this change as breaking in the changelog …
=> Add Breaking Change for macOS Entitlement Requirement

CHANGELOG.md, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Hi,
I am the author of [flutter_soloud](https://github.com/alnitak/flutter_soloud) plugin. Has been reported that when the audio player has already been initialized, an error occurs when trying to use `getDirectoryPath` in this [issue](https://github.com/alnitak/flutter_soloud/issues/180) with this error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Error 0x80010106: Cannot change thread mode after it is set.
```
This should fix the issue under Windows that could be raised when another plugin uses `CoInitializeEx` and the File Explorer window doesn't pop up.
Digging around and searching on the web, I found that it's safe to use an already created COM and this PR checks this case, but I'm not familiar with Windows, so it might be worth doing a bit more …
=> Windows fix: already initialized COM theading

CHANGELOG.md, lib/src/windows/file_picker_windows.dart, pubspec.yaml
I’m the original reporter of https://github.com/alnitak/flutter_soloud/issues/180. Even with the previous fix, we continued seeing the following error in production: 
> comdlg32.dll exception code 0xc000005
After further investigation, I discovered that the issue was related to COM initialization on the main thread. If COM is initialized on the main thread, we should **not** call `CoUninitialize`, as it may affect other components relying on COM.
To prevent this issue, the best approach is to run `getDirectoryPath` in its own isolate. This allows us to safely initialize and release COM within the isolate without impacting the main thread or other parts of the application.
Additionally, I added `finally` blocks to properly release allocated memory and ensure cleanup happens reliably.
This …
=> fix: Run `getDirectoryPath` in its own isolate to avoid COM initialization issues

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java, pubspec.yaml
This PR fixes file streams not getting closed.
The issue resulted in the android app process being killed if a file was picked from an USB device, then the device was ejected.
=> fix: file streams not getting closed

CHANGELOG.md, android/build.gradle, android/proguard-rules.pro, pubspec.yaml
Resolves [#1721](https://github.com/miguelpruivo/flutter_file_picker/issues/1721):
- Added `consumerProguardFiles` in `android/build.gradle`
- Created `proguard-rules.pro` in the `android/` folder
- Updated CHANGELOG.md to reflect the improvement
- Users no longer need to manually add ProGuard rules for `androidx.lifecycle.DefaultLifecycleObserver`
=> Add ProGuard consumer rules to avoid manual configuration

CHANGELOG.md, README.md, example/lib/src/file_picker_demo.dart, lib/_internal/file_picker_web.dart, lib/src/file_picker.dart, pubspec.yaml
This PR adds support for the `saveFile` method on web platforms. Previously, calling `saveFile` on web resulted in an `UnimplementedError`. Now, this method triggers a file download using the provided `bytes` and `fileName`.  
- Implemented file download functionality for web using `AnchorElement`.  
- Added validation to ensure `fileName` and `bytes` are provided, throwing an `ArgumentError` otherwise.  
- Updated method documentation to reflect web-specific behavior.  
- **Required parameters:** `fileName` and `bytes`.  
- **Functionality:** Downloads the file using a browser download prompt.  
- **Error handling:**  
- If `fileName` is `null` or does not include an extension, an `ArgumentError` is thrown.  
- If `bytes` is `null`, an `ArgumentError` is thrown.  
```dart
await …
```
=> Implement saveFile for Web

CHANGELOG.md, lib/src/file_picker.dart, lib/src/file_picker_macos.dart, lib/src/linux/file_picker_linux.dart, lib/src/utils.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
On **desktop platforms**, when `bytes` is provided:
1. The save dialog opens as usual.
2. If a path is selected, the provided `bytes` are written to the file.
3. The file path is returned (matching mobile behavior).
This modification improves cross-platform consistency, allowing developers to use `saveFile` without needing platform-specific logic.
- Verified the new behavior on **Windows, macOS, and Linux**.
- Ensured existing functionality on mobile remains unchanged.
Fixes #1725
=> Fix: Ensure `saveFile` writes bytes on desktop platforms

CHANGELOG.md, lib/src/file_picker.dart, macos/file_picker/Sources/file_picker/FilePickerPlugin.swift, pubspec.yaml
In #1718, I described that on macOS, the file_picker panels pause the parent app's run loop. I did some investigation and found out that using a sheet modal to present the file_picker panels improves the user experience - opening and saving files is similar to what users see in other apps, and the run loop in the parent window is still running.
This PR adds the change needed to use the sheet modal - please let me know if this is something we could eventually have in file_picker.
Notes:
- With this change, the file_picker panels lose the dialog title.
- Documentation for beginSheetModal: https://developer.apple.com/documentation/appkit/nssavepanel/beginsheetmodal(for:completionhandler:)
The recordings show the different behavior.
Before change: …
=> Use sheet modal for panels on macOs

CHANGELOG.md, macos/file_picker/Sources/file_picker/FilePickerPlugin.swift, pubspec.yaml
**Description:**
This PR addresses an issue where the `NSSavePanel` was not appearing when invoking the file picker on macOS. The root cause was an entitlement issue that was not properly handled, making it unclear why the panel failed to initialize. Now, the plugin correctly checks for the required entitlements (`com.apple.security.files.user-selected.read-write` or `com.apple.security.files.user-selected.read-only`) and returns an appropriate error if they are missing.
**Changes:**
- Implemented `checkEntitlement(requiredMode: EntitlementMode, result: @escaping FlutterResult)` to verify if the app has the correct entitlements before invoking `NSSavePanel`.
- Ensured that `NSSavePanel` is only initialized if the required entitlements are available.
- If entitlements are missing, the …
=> NSSavePanel Not Appearing Due to Missing Entitlements Handling

CHANGELOG.md, macos/file_picker/Sources/file_picker/FilePickerPlugin.swift, pubspec.yaml
`contentViewController` might be replaced by objects which are not `FlutterViewController`. In that the file_picker plugin fails to open needed dialogs.
This fix avoids checking the type and returns the views window.
Fixes #1739
=> [macOS] Ignore view controller type

CHANGELOG.md, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java, android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java, example/lib/src/file_picker_demo.dart, ios/file_picker/Sources/file_picker/FilePickerPlugin.m, ios/file_picker/Sources/file_picker/ImageUtils.m, lib/_internal/file_picker_web.dart, lib/src/file_picker.dart, lib/src/file_picker_io.dart, lib/src/file_picker_macos.dart, lib/src/linux/file_picker_linux.dart, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Fixes https://github.com/miguelpruivo/flutter_file_picker/issues/1742
Fixes https://github.com/miguelpruivo/flutter_file_picker/issues/1743
=> Changed compressionQuality by default to 0

android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FilePickerPlugin.kt
The bug cause the onFileLoading callback not invoking, and the logcat ouput:
```
E/EventChannel#miguelruivo.flutter.plugins.filepickerevent( 1376): Failed to open event stream
E/EventChannel#miguelruivo.flutter.plugins.filepickerevent( 1376): java.lang.NullPointerException: Parameter specified as non-null is null: method com.mr.flutter.plugin.filepicker.FilePickerPlugin$setup$1$1.onListen, parameter arguments
E/EventChannel#miguelruivo.flutter.plugins.filepickerevent( 1376): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$setup$1$1.onListen(Unknown Source:2)
E/EventChannel#miguelruivo.flutter.plugins.filepickerevent( 1376): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218) …
```
=> fixed event channel bug

CHANGELOG.md, ios/file_picker/Sources/file_picker/FilePickerPlugin.m, pubspec.yaml
When the iOS plugin detects that a method call is already in progress it returns a error result for the subsequent call **but sets the previously saved `_result` to `nil`**.
This causes a native app crash when the first (inprogress call) calls `- (void)documentPickerWasCancelled` as it tries to call `_result(nil)` but _result has been set to `nil` from the subsequent call. Fixes https://github.com/miguelpruivo/flutter_file_picker/issues/1626
This also fixes an issue where in dart if you call FilePicker.platform.saveFile twice without waiting for the first call to finish and you catch the exception from the second call, that the first call's future will never resolve (as the _result was nilled by the second call).
Example of this second issue
```dart
String? pickedSaveFilePath;
final …
```
=> Dont clear _result of previous method call when multiple method calls are performed at once on iOS

CHANGELOG.md, lib/_internal/file_picker_web.dart, pubspec.yaml
Memory leak is happening on web
<details>
<summary>See here</summary>
```Dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
void main() => runApp(const MyApp());
class MyApp extends StatelessWidget {
const MyApp({super.key});
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Material App',
home: FirstPage(),
);
}
}
class FirstPage extends StatelessWidget {
const FirstPage({super.key});
@override
Widget build(BuildContext context) {
return Scaffold(
body: Center(
child: TextButton(
onPressed: () {
Navigator.push(
context,
MaterialPageRoute(
builder: (context) => SecondPage(),
),
);
},
child: Text('Go'),
),
),
);
}
}
class SecondPage extends StatefulWidget {
const SecondPage({super.key});
@override
State<SecondPage> …
```
=> [Web] Dispose `filesCompleter` to avoid memory leak

CHANGELOG.md, android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FileUtils.kt, pubspec.yaml
This change fixes #1801.
Tested with a flash drive connected over OTG to Android phone and also external SD Card in Amazon Fire tablet.
=> correct external storage folder path on Android

lib/src/windows/file_picker_windows.dart, pubspec.yaml, test/common.dart
This PR improves the overall code quality and maintainability of the project by introducing `flutter_lints` and addressing the issues it identified.
*   Added the `flutter_lints` package to `dev_dependencies` to enforce modern Dart and Flutter styling conventions.
*   Ran `dart fix --apply` and manually fixed all new linter warnings across the codebase.
*   This includes changes such as:
*   Adding `void` to some missing functions.
*   Correcting Regexp annotation on Windows.
This effort ensures the code is more consistent, readable, and less prone to common errors.
=> chore: Enable flutter_lints and fix warnings

CHANGELOG.md, android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FileUtils.kt, pubspec.yaml
This PR addresses [Issue #1843](https://github.com/miguelpruivo/flutter_file_picker/issues/1843), where Android appends a `.txt` extension to files when using the MIME type `text/plain`, even if a different extension is specified in `Intent.EXTRA_TITLE`.
On Android, when using `Intent.ACTION_CREATE_DOCUMENT` with MIME type set to `text/plain`, the system automatically assumes the file must have a `.txt` extension. This results in filenames like:
- `config.json` → `config.json.txt`
- `data.csv` → `data.csv.txt`
This behavior affects users saving structured text data such as JSON, CSV, or log files, where the extension is semantically important.
To resolve this, we now:
- Detect when the MIME type is `text/plain`.
- Override it with the generic wildcard `*/*`.
This instructs Android not to …
=> fix(android): Use wildcard MIME type for plain text to preserve file extensions

.github/workflows/main.yml, lib/src/windows/file_picker_windows.dart, pubspec.yaml
Introduces a single “CI Pipeline” workflow triggered on pushes and pull requests to master.
- Job `test_flutter_versions` (Ubuntu) runs against Flutter 3.24.0, 3.27.0, 3.29.0, 3.32.0, and stable.
- Job `test_os_matrix` runs on ubuntu-latest, windows-latest, and macos-latest using the stable channel.
- Each job checks out code, sets up Flutter (subosito/flutter-action@v2), installs deps, verifies formatting, runs flutter analyze, and executes flutter test.
- Ensures compatibility across supported Flutter versions and platforms and prevents regressions.
=> Add matrix CI for Flutter versions

CHANGELOG.md, android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FilePickerDelegate.kt, android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FilePickerPlugin.kt, android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FileUtils.kt, pubspec.yaml
Summary
- When `MimeTypeMap` cannot resolve one or more custom extensions to a MIME type, the plugin now adds `[*/*]` into `Intent.EXTRA_MIME_TYPES` instead of failing or passing an invalid/empty list.
- Refactored saveFile implementation reorganizing the implementation following same flow. 
Rationale
- `MimeTypeMap.getMimeTypeFromExtension` can return `null` for custom types (e.g., `.quiz`, `.maso`). On some devices like Chromebooks, this leads to inconsistent behavior. Not applying a restrictive filter is preferable to silently failing.
Notes
- No Dart API changes.
- Behavior only changes when the allowed extensions cannot be resolved to known MIME types; otherwise, MIME filters are applied as before.
This resolve: https://github.com/miguelpruivo/flutter_file_picker/issues/1858
=> Android: Avoid MIME filter error when custom MIME types are unknown

android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FileUtils.kt
This fixes an issue on Android where the file picker does not allow CSV files to be picked when using the Custom option.
=> Fix picking CSV files on Android

.github/workflows/pub.yml, CHANGELOG.md, lib/src/file_picker_io.dart
This pull request restores the previous workflow for publishing packages to pub.dev. Since we still need Miguel to change the settings on pub.dev and he is currently OOO, we are reverting to the old mechanism to publish version 10.3.0. It also updates the changelog to include a web-specific feature and improves resource management in the IO file picker implementation. The most important changes are summarized below:
**CI/CD Automation:**
* Added a new GitHub Actions workflow (`.github/workflows/pub.yml`) to automate publishing the package to pub.dev when changes are pushed to the `master` branch, including credential setup and publishing steps.
**Added entry:**
* Updated `CHANGELOG.md` to document the introduction of a boolean flag that controls upload behavior on window blur for the web …
=> Release 10.3.0
