- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Classes/FilePickerPlugin.h
- ios/Classes/FilePickerPlugin.m
> adds iOS support

- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java
- example/lib/main.dart
- ios/Classes/FilePickerPlugin.h
- ios/Classes/FilePickerPlugin.m
- ios/Classes/FileUtils.h
- ios/Classes/FileUtils.m
- lib/file_picker.dart
* **Adds:** Support for video files.
> Video support

- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java
- android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
* **Fix:**  an issue where documents with some string path couldn't be loaded on the android 8.0.
> working on a bug fix

- lib/file_picker.dart
> If file not choosen getFile() should return null

- CHANGELOG.md
- README.md
- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java
- android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
- pubspec.yaml
fixes an issue that could prevent internal storage files from being properly picked
> see changelog (v1.4.0+1)

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java
- android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
- example/lib/src/file_picker_demo.dart
- lib/file_picker.dart
- pubspec.yaml
- Adds support for Android V2 embedding;
- Refactors FileType to match lower camelCase Dart guideline;
> Android V2 embedding

- file_picker/CHANGELOG.md
- file_picker/go/file_darwin.go
- file_picker/go/file_linux.go
- file_picker/go/file_unsupported.go
- file_picker/go/file_windows.go
- file_picker/go/plugin.go
- file_picker/pubspec.yaml
> #294 Adds getDirectoryPath() desktop implementation.

- file_picker_web/lib/file_picker_web.dart
Current version does not work on the iPhone with iOS 13.4.
To receive onChange event on the iPhone, we need to add Input element to the page body.
> Add support for Safari Mobile iOS

- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
- ios/Classes/FilePickerPlugin.m
This PR fixes the problem with directory pick on Android 9 or lower
> Fixes directory pick on Android 9 or lower (#425)

- ios/Classes/FilePickerPlugin.m
Does this fix resolve https://github.com/miguelpruivo/flutter_file_picker/issues/531 ? Please confirm.
> Update preferredAssetRepresentationMode to PHPickerViewController for video.

- go/README.md
made plugins path proper one :)
> fixed the path :)

- lib/src/platform_file.dart
#751 
i have searched on the web and on this repository issues and i cant figure out why 
i didn't read the docs very will i thought that file picker will only need the permissions  😐
but i was wrong 😅😅
i have made some changes to make it clear for others to figure it out it easily 
now no one will buzzer you with this issue any more 😅😅
> fix PlatformFile path is always null on web

- CHANGELOG.md
- lib/src/file_picker_linux.dart
- pubspec.yaml
- test/file_picker_linux_test.dart
> Bug: incorrect file filter on Linux

- CHANGELOG.md
- lib/src/file_picker_macos.dart
- pubspec.yaml
- test/file_picker_macos_test.dart
> #890: cannot pick filenames with comma followed by blank

- lib/src/file_picker_linux.dart
This should cover all FilePicker functionalities for KDE Plasma distributions, as KDE Plasma ships with `kdialog` for scripting based operations. Even though `qarma` is Qt implementation of `zenity`, I could not find any KDE Plasma distro that is still utilizing `qarma` for file system manipulations.
Please note: I have found that, `kdialog` is not correctly handling file filter MIME types, where it **CAN** accept filters as String (eg : `'*.ogg *.mp4'` etc), but does not filter them unless addressing MIME types in `'video/ogg video/mp4'` this format. I will be filing a bug on KDE gitlab addressing this issue. So I did not change anything regarding file filter types.
I am trying to achieve `kdialog` functionalities with minimal changes and being new to software development, am willing to …
> Added kdialog arguments

- lib/src/file_picker_linux.dart
Reverts miguelpruivo/flutter_file_picker#932
> Revert "Added kdialog arguments"

- CHANGELOG.md
- ios/Classes/FileUtils.m
- pubspec.yaml
> Handle `UTTypeCreatePreferredIdentifierForTag` returning `NULL`

- CHANGELOG.md
- android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java
- pubspec.yaml
> replaced random with timestamp

- ios/Classes/FilePickerPlugin.m
- ios/Classes/ImageUtils.h
- ios/Classes/ImageUtils.m
I have separated the metadata first then append it with the image then saved it to a temporary directory.
> Image picking fail issue solved for live images on newer IOS.

- CHANGELOG.md
- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
- example/android/app/build.gradle
- pubspec.yaml
Fixes #1138
@miguelpruivo I could not test the change on an emulator due to a conflict with the NDK (I have a newer version installed than what the example app wants). Could you look into that?
> Fix parcelable deprecation

- ios/file_picker.podspec
https://github.com/miguelpruivo/flutter_file_picker/issues/1208
> Fix preprocessor definitions in podspec

- CHANGELOG.md
- lib/_internal/file_picker_web.dart
- pubspec.yaml
A quick and dirty solution to fix the timeout on slow machines:
https://github.com/miguelpruivo/flutter_file_picker/issues/1197
> Web: Increase time to wait on JS result

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- lib/src/windows/file_picker_windows.dart
- lib/src/windows/file_picker_windows_ffi_types.dart
- pubspec.yaml
> #989: save file on Windows: prompt user for confirmation when selecting an already existing file

- android/src/main/AndroidManifest.xml
> Add `maxSdkVersion`

- .github/workflows/maintainer.yml
Fixed the issue where the actual stale time does not match the displayed stale time.
> Fix stale-issue-message description error

- README.md
> Docs: wrong Multi file picker usage

- android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java
Fixed an issue that always returned null when selecting files on Redmi NOTE 9
> Fixed an issue where null was returned when picking up files

- ios/file_picker/Sources/file_picker/FilePickerPlugin.m
Fix https://github.com/miguelpruivo/flutter_file_picker/issues/1761
> Using the self property instead of a local variable

- CHANGELOG.md
- pubspec.yaml
- Fixed an issue loading files. [#1777](https://github.com/miguelpruivo/flutter_file_picker/pull/1777)
> Release 10.1.3

- android/src/main/kotlin/com/mr/flutter/plugin/filepicker/FileUtils.kt
fix https://github.com/miguelpruivo/flutter_file_picker/issues/1767
> Fix the repetition of folder paths obtained in Android

- CHANGELOG.md
- pubspec.yaml
This resolve: 
- https://github.com/miguelpruivo/flutter_file_picker/issues/1767 
- https://github.com/miguelpruivo/flutter_file_picker/issues/1774. (Resolved)
Both are the same issue.
> Release 10.1.4

- pubspec.yaml
Release a new version with:
- https://github.com/miguelpruivo/flutter_file_picker/pull/1798
> Release 10.1.7

- .github/workflows/main.yml
-fixed: https://github.com/miguelpruivo/flutter_file_picker/issues/1864
> Run format check only on stable Flutter
